version: '3.7'
services:
  simba-task:
    image: simba-task
    build: .
    env_file: .env
    restart: always
    volumes:
      - ./public:/app/public
    ports:
      - '3000:3000'
    depends_on:
      - simba-task-db
  simba-task-db:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - ./simba-task-db:/var/lib/postgres
      - ./externalVolumes/db:/data/db
